common: &common
  adapter: postgresql
  username: postgres
  password: root
  encoding: UTF8
  host: 127.0.0.1
production:
  database: crm_prod
  host: 127.0.0.1
  <<: *common
development:
  database: crm_demo
  <<: *common
test:
  database: crm_test
  <<: *common
